### ISSUE TITLE
Road to v1.0

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonySDK#144]
# TODO

- [x] Merge open PRs
- [x] Advanced example guide
- [x] Add "where to go from here", link to advanced example, guides, API, tx guide
- [x] Fix guides (new API)
- [x] Add guide for metadata (maybe use create transactions guide), link to it from all metadata transactions
- [x] Adjust colonyStarter (also example and docs)
- [x] Adjust IPFS adapter examples (e.g. https://docs.colony.io/next/colonysdk/api/classes/PinataAdapter)
- [x] Release 1.0 :tada:
